<?php

namespace AdminBundle\Repository;

/**
 * TatooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TatooRepository extends \Doctrine\ORM\EntityRepository
{
}
